# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.1
  - 1.2
  - nightly
matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true
notifications:
  email: false

# install:
#   - wget http://home.zcu.cz/~mjirik/lisa/install/install_conda.sh && source install_conda.sh
#   - conda list
#
#   - conda create --yes -n travis -c mjirik -c conda-forge python=3 pandas
#   - source activate travis
#   - julia -e 'using Pkg; Pkg.add("PyCall"); ENV["PYTHON"] = read(`which python`, String)[1:end-1]; Pkg.build("PyCall")'

after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
